CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    category_id BIGINT,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_stock_movements_product
        FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_stock_movements_product_id ON stock_movements (product_id);
